// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VeraConstrucoes.Infrastructure.Data;

#nullable disable

namespace VeraConstrucoes.Infrastructure.Migrations
{
    [DbContext(typeof(VeraConstrucoesContext))]
    [Migration("20260313222041_Campo Status Nota Fiscal2")]
    partial class CampoStatusNotaFiscal2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("VeraConstrucoes.Domain.Entities.Configuracoes.ConfiguracaoNFCe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Ambiente")
                        .HasColumnType("int");

                    b.Property<string>("BairroEmitente")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("CEP")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("CSC")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("CaminhoCertificado")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("CnpjEmitente")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("CodigoMunicipioIBGE")
                        .HasColumnType("int");

                    b.Property<string>("ComplementoEmitente")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<string>("IdCSC")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("InscricaoEstadual")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("IntervaloConsultaRecibo")
                        .HasColumnType("int");

                    b.Property<string>("LogradouroEmitente")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("NomeFantasia")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("NomeMunicipio")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NumeroEmitente")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("PastaDanfes")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("PastaXmlAutorizados")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("PastaXmlCancelados")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("PastaXmlEnviados")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<int>("RegimeTributario")
                        .HasColumnType("int");

                    b.Property<string>("SenhaCertificado")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("SerieNota")
                        .HasColumnType("int");

                    b.Property<long>("Telefone")
                        .HasColumnType("bigint");

                    b.Property<int>("TentativasConsultaRecibo")
                        .HasColumnType("int");

                    b.Property<int>("TimeoutTransmissao")
                        .HasColumnType("int");

                    b.Property<int>("TipoEmissao")
                        .HasColumnType("int");

                    b.Property<string>("UF")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)");

                    b.Property<int>("UltimoNumeroNota")
                        .HasColumnType("int");

                    b.Property<int>("UnidadeFederativaCodigo")
                        .HasColumnType("int");

                    b.Property<int>("Versao")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ConfiguracoesNFCe");
                });

            modelBuilder.Entity("VeraConstrucoes.Domain.Entities.NCM.NCM", b =>
                {
                    b.Property<string>("Ncm")
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.Property<int>("csosn")
                        .HasColumnType("int(6)");

                    b.Property<string>("descricao")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Ncm");

                    b.ToTable("NCM");
                });

            modelBuilder.Entity("VeraConstrucoes.Domain.Entities.NFCe.NFC", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClienteDocumento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("ClienteEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ClienteNome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ClienteTelefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("DataEmissao")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<int>("Serie")
                        .HasColumnType("int");

                    b.Property<string>("SituacaoNota")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)");

                    b.Property<bool>("StatusProcessamento")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("NFCes");
                });

            modelBuilder.Entity("VeraConstrucoes.Domain.Entities.NFCe.NFCePropriedades", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("Acrescimo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ChaveAcesso")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("Desconto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MensagemErro")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("NFCeId")
                        .HasColumnType("int");

                    b.Property<string>("Observacoes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("PdfPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Protocolo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("QrCodeUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("XmlPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("NFCeId")
                        .IsUnique();

                    b.ToTable("NFCePropriedades");
                });

            modelBuilder.Entity("VeraConstrucoes.Domain.Entities.NFCe.PagamentoNF", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Bandeira")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Metodo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("NFCeId")
                        .HasColumnType("int");

                    b.Property<int>("Parcelas")
                        .HasColumnType("int");

                    b.Property<decimal>("Troco")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("NFCeId");

                    b.ToTable("PagamentoNFCes");
                });

            modelBuilder.Entity("VeraConstrucoes.Domain.Entities.NFCe.ProdutoNF", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Cest")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("varchar(7)");

                    b.Property<int>("Cfop")
                        .HasMaxLength(4)
                        .HasColumnType("int");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("NFCeId")
                        .HasColumnType("int");

                    b.Property<string>("Ncm")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.Property<decimal>("Quantidade")
                        .HasColumnType("decimal(18,3)");

                    b.Property<string>("Unidade")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("varchar(6)");

                    b.Property<decimal>("ValorUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("NFCeId");

                    b.ToTable("ProdutoNF");
                });

            modelBuilder.Entity("VeraConstrucoes.Domain.Entities.Produtos.Produto", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Ncm")
                        .HasColumnType("varchar(8)");

                    b.Property<string>("descricao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("estoque")
                        .HasColumnType("int");

                    b.Property<decimal>("valorUnitario")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("id");

                    b.HasIndex("Ncm");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("VeraConstrucoes.Domain.Entities.NFCe.NFCePropriedades", b =>
                {
                    b.HasOne("VeraConstrucoes.Domain.Entities.NFCe.NFC", "NFCe")
                        .WithOne("Complemento")
                        .HasForeignKey("VeraConstrucoes.Domain.Entities.NFCe.NFCePropriedades", "NFCeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NFCe");
                });

            modelBuilder.Entity("VeraConstrucoes.Domain.Entities.NFCe.PagamentoNF", b =>
                {
                    b.HasOne("VeraConstrucoes.Domain.Entities.NFCe.NFC", "NFCe")
                        .WithMany("Pagamentos")
                        .HasForeignKey("NFCeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NFCe");
                });

            modelBuilder.Entity("VeraConstrucoes.Domain.Entities.NFCe.ProdutoNF", b =>
                {
                    b.HasOne("VeraConstrucoes.Domain.Entities.NFCe.NFC", "NFCe")
                        .WithMany("Produtos")
                        .HasForeignKey("NFCeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NFCe");
                });

            modelBuilder.Entity("VeraConstrucoes.Domain.Entities.Produtos.Produto", b =>
                {
                    b.HasOne("VeraConstrucoes.Domain.Entities.NCM.NCM", "ncm")
                        .WithMany()
                        .HasForeignKey("Ncm");

                    b.Navigation("ncm");
                });

            modelBuilder.Entity("VeraConstrucoes.Domain.Entities.NFCe.NFC", b =>
                {
                    b.Navigation("Complemento")
                        .IsRequired();

                    b.Navigation("Pagamentos");

                    b.Navigation("Produtos");
                });
#pragma warning restore 612, 618
        }
    }
}
